# Site Settings
title: "openMHA"
email: "hendrikkayser@openMHA.org"
description: "openMHA"
baseurl: ""
url: "localhost:4000"
repository: "HoerTech-gGmbH/openMHA"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
  hard_wrap: false
gems: