# Site Settings
title: "openMHA"
email: "hendrikkayser@openMHA.org"
description: "Open tools for hearing aid development."
baseurl: "http://www.openMHA.org"
url: "http://www.openMHA.org"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
  hard_wrap: false
gems: