# Site Settings
title: openMHA
email: hendrik.kayser@uol.de
description: >
  Open tools for hearing aid development.
baseurl: "http://www.openMHA.org"
url: "http://www.openMHA.org"
github_username:  hoertech
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

theme: jekyll-theme-slate